/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oscar
 */
public class Proyectos extends javax.swing.JFrame {

    /**
     * Creates new form Proyectos
     */
    public Proyectos() {
        initComponents();
        new Cproyectos().mostrarProyecto(Tb_clientes3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tb_clientes3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        panel_login12 = new javax.swing.JPanel();
        login_btm14 = new javax.swing.JLabel();
        panel_login13 = new javax.swing.JPanel();
        login_btm15 = new javax.swing.JLabel();
        panel_login14 = new javax.swing.JPanel();
        login_btm16 = new javax.swing.JLabel();
        Campo_combo3 = new javax.swing.JComboBox<>();
        Registro_field3 = new javax.swing.JTextField();
        panel_login15 = new javax.swing.JPanel();
        login_btm17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(245, 101, 90));

        Tb_clientes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tb_clientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_clientes3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tb_clientes3);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proyectos");

        panel_login12.setBackground(new java.awt.Color(246, 150, 143));
        panel_login12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login12MouseExited(evt);
            }
        });

        login_btm14.setBackground(new java.awt.Color(247, 199, 196));
        login_btm14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm14.setForeground(new java.awt.Color(249, 249, 249));
        login_btm14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm14.setText("INSERTAR");
        login_btm14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login12Layout = new javax.swing.GroupLayout(panel_login12);
        panel_login12.setLayout(panel_login12Layout);
        panel_login12Layout.setHorizontalGroup(
            panel_login12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login12Layout.setVerticalGroup(
            panel_login12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_login13.setBackground(new java.awt.Color(246, 150, 143));
        panel_login13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login13MouseExited(evt);
            }
        });

        login_btm15.setBackground(new java.awt.Color(247, 199, 196));
        login_btm15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm15.setForeground(new java.awt.Color(249, 249, 249));
        login_btm15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm15.setText("RECARGAR");
        login_btm15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login13Layout = new javax.swing.GroupLayout(panel_login13);
        panel_login13.setLayout(panel_login13Layout);
        panel_login13Layout.setHorizontalGroup(
            panel_login13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_btm15, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        panel_login13Layout.setVerticalGroup(
            panel_login13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_login14.setBackground(new java.awt.Color(246, 150, 143));
        panel_login14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login14MouseExited(evt);
            }
        });

        login_btm16.setBackground(new java.awt.Color(247, 199, 196));
        login_btm16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm16.setForeground(new java.awt.Color(249, 249, 249));
        login_btm16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm16.setText("BUSCAR");
        login_btm16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login14Layout = new javax.swing.GroupLayout(panel_login14);
        panel_login14.setLayout(panel_login14Layout);
        panel_login14Layout.setHorizontalGroup(
            panel_login14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login14Layout.setVerticalGroup(
            panel_login14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Campo_combo3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Campo_combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "provedor_id", "nombre", "email", "telefono", "activo" }));
        Campo_combo3.setToolTipText("");
        Campo_combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_combo3ActionPerformed(evt);
            }
        });

        Registro_field3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Registro_field3.setBorder(null);

        panel_login15.setBackground(new java.awt.Color(246, 150, 143));
        panel_login15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login15MouseExited(evt);
            }
        });

        login_btm17.setBackground(new java.awt.Color(247, 199, 196));
        login_btm17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm17.setForeground(new java.awt.Color(249, 249, 249));
        login_btm17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm17.setText("MODIFICAR");
        login_btm17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm17.setEnabled(false);
        login_btm17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login15Layout = new javax.swing.GroupLayout(panel_login15);
        panel_login15.setLayout(panel_login15Layout);
        panel_login15Layout.setHorizontalGroup(
            panel_login15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login15Layout.setVerticalGroup(
            panel_login15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(panel_login12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_login15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_login13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Campo_combo3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Registro_field3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_login14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_login15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_login12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_login13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_login14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Campo_combo3)
                    .addComponent(Registro_field3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tb_clientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_clientes3MouseClicked
        // TODO add your handling code here:
        new Cprovedores().SeleccionarProvedor(Tb_clientes3, Registro_field3, Campo_combo3);
       // String id = seleccionarParam(Tb_clientes3, 0);
        String mnombre = new Cpersonal().seleccionarParam(Tb_clientes3, 1);
        String memail = new Cpersonal().seleccionarParam(Tb_clientes3, 2);
        String mtel = new Cpersonal().seleccionarParam(Tb_clientes3, 3);
        String mact = new Cpersonal().seleccionarParam(Tb_clientes3, 4);

       // mod3.setProvedorMod(id, mnombre, memail, mtel, mact);

        login_btm17.setEnabled(true);
    }//GEN-LAST:event_Tb_clientes3MouseClicked

    private void login_btm14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseClicked
        try {
            new proyectos_insert().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Proyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_btm14MouseClicked

    private void login_btm14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm14MouseEntered

    private void login_btm14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm14MouseExited

    private void panel_login12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login12MouseEntered

    private void panel_login12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login12MouseExited

    private void login_btm15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseClicked
        // TODO add your handling code here:
        new Cproyectos().mostrarProyecto(Tb_clientes3);
    }//GEN-LAST:event_login_btm15MouseClicked

    private void login_btm15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm15MouseEntered

    private void login_btm15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm15MouseExited

    private void panel_login13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login13MouseEntered

    private void panel_login13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login13MouseExited

    private void login_btm16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseClicked
        // TODO add your handling code here:
        new Cprovedores().BuscarProvedor(Tb_clientes3, Campo_combo3, Registro_field3);
        Campo_combo3.setSelectedIndex(0);
        Registro_field3.setText("");
    }//GEN-LAST:event_login_btm16MouseClicked

    private void login_btm16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm16MouseEntered

    private void login_btm16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm16MouseExited

    private void panel_login14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login14MouseEntered

    private void panel_login14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login14MouseExited

    private void Campo_combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_combo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_combo3ActionPerformed

    private void login_btm17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm17MouseClicked

    private void login_btm17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm17MouseEntered

    private void login_btm17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm17MouseExited

    private void panel_login15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login15MouseEntered

    private void panel_login15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login15MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Campo_combo3;
    private javax.swing.JTextField Registro_field3;
    private javax.swing.JTable Tb_clientes3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel login_btm14;
    private javax.swing.JLabel login_btm15;
    private javax.swing.JLabel login_btm16;
    private javax.swing.JLabel login_btm17;
    private javax.swing.JPanel panel_login12;
    private javax.swing.JPanel panel_login13;
    private javax.swing.JPanel panel_login14;
    private javax.swing.JPanel panel_login15;
    // End of variables declaration//GEN-END:variables
}
