/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oscar
 */
public class Proyectos extends javax.swing.JFrame  {

    /**
     * Creates new form Proyectos
     * @throws java.sql.SQLException
     */
     proyectos_mod mod = new proyectos_mod();
    private int Ymouse;
    private int Xmouse;
    public Proyectos() throws SQLException {
        initComponents();
        new Cproyectos().mostrarProyecto(Tb_clientes3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_label = new javax.swing.JLabel();
        exit_label1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tb_clientes3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        panel_login12 = new javax.swing.JPanel();
        login_btm14 = new javax.swing.JLabel();
        panel_login13 = new javax.swing.JPanel();
        login_btm15 = new javax.swing.JLabel();
        panel_login14 = new javax.swing.JPanel();
        login_btm16 = new javax.swing.JLabel();
        Campo_combo3 = new javax.swing.JComboBox<>();
        Registro_field3 = new javax.swing.JTextField();
        panel_login15 = new javax.swing.JPanel();
        login_btm17 = new javax.swing.JLabel();
        selector1 = new javax.swing.JPanel();
        exit_panel = new javax.swing.JPanel();
        exit_label2 = new javax.swing.JLabel();

        exit_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit_label.setForeground(new java.awt.Color(255, 255, 255));
        exit_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_label.setText("X");
        exit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });

        exit_label1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit_label1.setForeground(new java.awt.Color(255, 255, 255));
        exit_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_label1.setText("X");
        exit_label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_label1MouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(245, 101, 90));

        Tb_clientes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tb_clientes3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_clientes3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tb_clientes3);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proyectos");

        panel_login12.setBackground(new java.awt.Color(246, 150, 143));
        panel_login12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login12MouseExited(evt);
            }
        });

        login_btm14.setBackground(new java.awt.Color(247, 199, 196));
        login_btm14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm14.setForeground(new java.awt.Color(249, 249, 249));
        login_btm14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm14.setText("INSERTAR");
        login_btm14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login12Layout = new javax.swing.GroupLayout(panel_login12);
        panel_login12.setLayout(panel_login12Layout);
        panel_login12Layout.setHorizontalGroup(
            panel_login12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login12Layout.setVerticalGroup(
            panel_login12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_login13.setBackground(new java.awt.Color(246, 150, 143));
        panel_login13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login13MouseExited(evt);
            }
        });

        login_btm15.setBackground(new java.awt.Color(247, 199, 196));
        login_btm15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm15.setForeground(new java.awt.Color(249, 249, 249));
        login_btm15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm15.setText("RECARGAR");
        login_btm15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login13Layout = new javax.swing.GroupLayout(panel_login13);
        panel_login13.setLayout(panel_login13Layout);
        panel_login13Layout.setHorizontalGroup(
            panel_login13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_btm15, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        panel_login13Layout.setVerticalGroup(
            panel_login13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_login14.setBackground(new java.awt.Color(246, 150, 143));
        panel_login14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login14MouseExited(evt);
            }
        });

        login_btm16.setBackground(new java.awt.Color(247, 199, 196));
        login_btm16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm16.setForeground(new java.awt.Color(249, 249, 249));
        login_btm16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm16.setText("BUSCAR");
        login_btm16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login14Layout = new javax.swing.GroupLayout(panel_login14);
        panel_login14.setLayout(panel_login14Layout);
        panel_login14Layout.setHorizontalGroup(
            panel_login14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login14Layout.setVerticalGroup(
            panel_login14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Campo_combo3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Campo_combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "id", "nombre", "fecha_i", "fecha_f", "cliente", "maquina", "activo" }));
        Campo_combo3.setToolTipText("");
        Campo_combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_combo3ActionPerformed(evt);
            }
        });

        Registro_field3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Registro_field3.setBorder(null);

        panel_login15.setBackground(new java.awt.Color(246, 150, 143));
        panel_login15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_login15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_login15MouseExited(evt);
            }
        });

        login_btm17.setBackground(new java.awt.Color(247, 199, 196));
        login_btm17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_btm17.setForeground(new java.awt.Color(249, 249, 249));
        login_btm17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btm17.setText("MODIFICAR");
        login_btm17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btm17.setEnabled(false);
        login_btm17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btm17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btm17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btm17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_login15Layout = new javax.swing.GroupLayout(panel_login15);
        panel_login15.setLayout(panel_login15Layout);
        panel_login15Layout.setHorizontalGroup(
            panel_login15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_login15Layout.setVerticalGroup(
            panel_login15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_login15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btm17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        selector1.setOpaque(false);
        selector1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                selector1MouseDragged(evt);
            }
        });
        selector1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selector1MousePressed(evt);
            }
        });

        exit_panel.setBackground(new java.awt.Color(27, 27, 27));
        exit_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_panelMouseExited(evt);
            }
        });

        exit_label2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit_label2.setForeground(new java.awt.Color(255, 255, 255));
        exit_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_label2.setText("X");
        exit_label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_label2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exit_panelLayout = new javax.swing.GroupLayout(exit_panel);
        exit_panel.setLayout(exit_panelLayout);
        exit_panelLayout.setHorizontalGroup(
            exit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exit_panelLayout.setVerticalGroup(
            exit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selector1Layout = new javax.swing.GroupLayout(selector1);
        selector1.setLayout(selector1Layout);
        selector1Layout.setHorizontalGroup(
            selector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selector1Layout.createSequentialGroup()
                .addComponent(exit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selector1Layout.setVerticalGroup(
            selector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(panel_login12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_login15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_login13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(65, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Campo_combo3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Registro_field3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_login14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128))))))
            .addComponent(selector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(selector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_login15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_login12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_login13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_login14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Campo_combo3)
                    .addComponent(Registro_field3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tb_clientes3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_clientes3MouseClicked
        // TODO add your handling code here:
        new Cproyectos().SeleccionarProyecto(Tb_clientes3, Registro_field3, Campo_combo3);
        String id = new Cpersonal().seleccionarParam(Tb_clientes3, 0);
        String mnombre = new Cpersonal().seleccionarParam(Tb_clientes3, 1);
        String fecha_i = new Cpersonal().seleccionarParam(Tb_clientes3, 2);
        String fecha_f = new Cpersonal().seleccionarParam(Tb_clientes3, 3);
        String cliente = new Cpersonal().seleccionarParam(Tb_clientes3, 4);
        String maquina = new Cpersonal().seleccionarParam(Tb_clientes3, 5);
        String activo = new Cpersonal().seleccionarParam(Tb_clientes3, 6);

       // mod3.setProvedorMod(id, mnombre, memail, mtel, mact);
       mod.setProyecto(id, mnombre, fecha_i, fecha_f, cliente, maquina, activo);
        login_btm17.setEnabled(true);
    }//GEN-LAST:event_Tb_clientes3MouseClicked

    private void login_btm14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseClicked
        try {
            new proyectos_insert().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Proyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_btm14MouseClicked

    private void login_btm14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm14MouseEntered

    private void login_btm14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm14MouseExited

    private void panel_login12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login12MouseEntered

    private void panel_login12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login12MouseExited

    private void login_btm15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseClicked
        // TODO add your handling code here:
        new Cproyectos().mostrarProyecto(Tb_clientes3);
    }//GEN-LAST:event_login_btm15MouseClicked

    private void login_btm15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm15MouseEntered

    private void login_btm15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm15MouseExited

    private void panel_login13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login13MouseEntered

    private void panel_login13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login13MouseExited

    private void login_btm16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseClicked
        // TODO add your handling code here:
        new Cproyectos().BuscarProyecto(Tb_clientes3, Campo_combo3, Registro_field3);
        Campo_combo3.setSelectedIndex(0);
        Registro_field3.setText("");
    }//GEN-LAST:event_login_btm16MouseClicked

    private void login_btm16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm16MouseEntered

    private void login_btm16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm16MouseExited

    private void panel_login14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login14MouseEntered

    private void panel_login14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login14MouseExited

    private void Campo_combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_combo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_combo3ActionPerformed

    private void login_btm17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseClicked
        // TODO add your handling code here:
        mod.setVisible(true);
    }//GEN-LAST:event_login_btm17MouseClicked

    private void login_btm17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm17MouseEntered

    private void login_btm17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btm17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btm17MouseExited

    private void panel_login15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login15MouseEntered

    private void panel_login15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_login15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_login15MouseExited

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        exit_panel.setBackground(Color.red);
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited

        exit_panel.setBackground(Color.decode("#1b1b1b"));
    }//GEN-LAST:event_exit_labelMouseExited

    private void exit_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_label1MouseClicked

    private void exit_label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label1MouseEntered
        exit_panel.setBackground(Color.red);
    }//GEN-LAST:event_exit_label1MouseEntered

    private void exit_label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label1MouseExited

        exit_panel.setBackground(Color.decode("#1b1b1b"));
    }//GEN-LAST:event_exit_label1MouseExited

    private void exit_label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label2MouseClicked
        setVisible(false);
    }//GEN-LAST:event_exit_label2MouseClicked

    private void exit_label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label2MouseEntered
        exit_panel.setBackground(Color.red);
    }//GEN-LAST:event_exit_label2MouseEntered

    private void exit_label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_label2MouseExited

        exit_panel.setBackground(Color.decode("#1b1b1b"));
    }//GEN-LAST:event_exit_label2MouseExited

    private void exit_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_panelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_panelMouseEntered

    private void exit_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_panelMouseExited
        exit_panel.setBackground(Color.black);
    }//GEN-LAST:event_exit_panelMouseExited

    private void selector1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selector1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - Xmouse, y - Ymouse);
    }//GEN-LAST:event_selector1MouseDragged

    private void selector1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selector1MousePressed
        Xmouse = evt.getX();
        Ymouse = evt.getY();
    }//GEN-LAST:event_selector1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Proyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Campo_combo3;
    private javax.swing.JTextField Registro_field3;
    private javax.swing.JTable Tb_clientes3;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel exit_label1;
    private javax.swing.JLabel exit_label2;
    private javax.swing.JPanel exit_panel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel login_btm14;
    private javax.swing.JLabel login_btm15;
    private javax.swing.JLabel login_btm16;
    private javax.swing.JLabel login_btm17;
    private javax.swing.JPanel panel_login12;
    private javax.swing.JPanel panel_login13;
    private javax.swing.JPanel panel_login14;
    private javax.swing.JPanel panel_login15;
    private javax.swing.JPanel selector1;
    // End of variables declaration//GEN-END:variables
}
